language: node_js
node_js:
 - "node"
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: deployment
